Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/homebrew/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
abf = pyabf.ABF(file_path)              # we load it
print(abf)                              # record characteristics 
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m abf [38;5;241m=[39m [43mpyabf[49m[38;5;241;43m.[39;49m[43mABF[49m[43m([49m[43mfile_path[49m[43m)[49m              [38;5;66;03m# we load it[39;00m
[1;32m      2[0m [38;5;28mprint[39m(abf)                              [38;5;66;03m# record characteristics [39;00m

File [0;32m/opt/homebrew/anaconda3/lib/python3.9/site-packages/pyabf/abf.py:100[0m, in [0;36mABF.__init__[0;34m(self, abfFilePath, loadData, cacheStimulusFiles, stimulusFileFolder)[0m
[1;32m     97[0m     [38;5;28mself[39m[38;5;241m.[39mstimulusFileFolder [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mabfFolderPath
[1;32m     99[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists([38;5;28mself[39m[38;5;241m.[39mabfFilePath):
[0;32m--> 100[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mABF file does not exist: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m [38;5;28mself[39m[38;5;241m.[39mabfFilePath)
[1;32m    101[0m [38;5;28mself[39m[38;5;241m.[39mabfID [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39msplitext(os[38;5;241m.[39mpath[38;5;241m.[39mbasename([38;5;28mself[39m[38;5;241m.[39mabfFilePath))[[38;5;241m0[39m]
[1;32m    103[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m([38;5;28mself[39m[38;5;241m.[39mabfFilePath, [38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m fb:
[1;32m    104[0m 
[1;32m    105[0m     [38;5;66;03m# The first 4 bytes of the ABF indicates what type of file it is[39;00m

[0;31mValueError[0m: ABF file does not exist: /Users/campillo/Documents/0-git.nosync/data-science-spikes/lhb_bursting/cell89basal.abf

